### ISSUE TITLE
Error in getting page height

### ISSUE THREAD

**Issue by rzecchini** [dieulot/instantclick#103]
When trying to get the whole page height (document.height or body.height) I'm getting wrong, smaller, values. If I reload the page it's ok.
I started that simple:
```javascript
var pageHeight = $("body").height();
console.log("page height " + pageHeight);
```
I also tried wrapping the code inside the change function
```javascript
InstantClick.on('change', function () {
var pageHeight = $("body").height();
console.log("page height " + pageHeight);
}
```
and give to the script a data-no-instant attribute, but it goes the same way. (I only obtain different wrong values)

**Comment by dieulot** [comment]
Thanks for the report (and sorry for the delay), but I’m not getting that problem with IC 3.1 and jQuery 2.1. What version of jQuery and IC are you using?

**Comment by rzecchini** [comment]
yep, I don't know if it could be some versioning problem or it was related to other parts of the script but now I'm not getting that error either. thanks
