### ISSUE TITLE
Breaks Prism.js and Highlight.js

### ISSUE THREAD

**Issue by AndyF** [dieulot/instantclick#107]
Instantclick breaks the formatting of all JS syntax highlighting plugins.

**Comment by BenBarber** [comment]
I resolved this issue when using Prism.js by calling the below method when the page is loaded. See http://prismjs.com/extending.html#api for reference

```javascript
Prism.highlightAll();
```

**Comment by dieulot** [comment]
I’ll have a look at that. Thanks for reporting this.

**Comment by AndyF** [comment]
@dieulot any progress on solving this bug? Seems like an issue with InstantClick turning pages into a single page application.

**Comment by dieulot** [comment]
Sorry for the delay – I want to, among other things, make a dedicated place on the website that explains how to solve that for each script who needs that. I have a lot of schlep work to do related to InstantClick (the project itself, not the code), so I’m procrastinating.

**Comment by AndyF** [comment]
Ah, it would be great if you could get that up soon, or if a potential fix could be posted here. @BenBarber 's approach unfortunately did not solve it for me.

**Comment by AndyF** [comment]
Found a fix for anyone getting highlighting conflicts.

`Prism.highlightAll()` needs to be called after `$(document).ready()`, preferably on the very last line.

**Comment by RickCogley** [comment]
hi @dieulot - sorry to ask such a newbie question, but, does the above mean adding the above fix to prism's basic script tag? :

    <script src="prism.js">
    Prism.highlightAll()
    </script>

Or, is this a matter of creating another script, just to call Prisl.highlightAll()? 

Thanks in advance.
