### ISSUE TITLE
[Suggest] A loading page

### ISSUE THREAD

**Issue by fy0** [dieulot/instantclick#125]
For be simple, I added all css/js file into my base template file.

So first load will take several seconds, I think a loading page can make users feel much better, just like AngularJs ...

**Comment by dieulot** [comment]
What do you mean by a loading page? I have no idea how things are done with AngularJS.

**Comment by fy0** [comment]
@dieulot  Almost 1 year .... I mean a loading page before everything is ready. But it doesn't matter now.

I already switch to some new frontend magics, and everthing were changed.
