### ISSUE TITLE
Scroll position bug in Chrome

### ISSUE THREAD

**Issue by ruricolist** [dieulot/instantclick#126]
In both Chrome and Opera, if you go to page A, scroll down, load page B with Instantclick, use the back button, and then load page C with Instantclick, the scroll position from page A propagates to page C.

To reproduce:
- Go to instantclick.io.
- Scroll down a little.
- Click on the changelog.
- Use the back button.
- Click on the changelog again.

The changelog page loads scrolled down by the same amount as the home page.

**Comment by dieulot** [comment]
I’m not seeing that problem. Are you still experiencing that problem?

**Comment by ruricolist** [comment]
No, I'm not. The underlying issue must have been fixed in Chrome.
