### ISSUE TITLE
Bug: Same link is added to history API multiple times 

### ISSUE THREAD

**Issue by robgraeber** [dieulot/instantclick#134]
Same link is added to history API multiple times. 

To reproduce: 

-Go to instantclick.io
-Click on the documentation multiple times
-Then hit the browser back button

It should go back to instantclick.io, but instead it stays on the same page.

**Comment by QuantumRevenger** [comment]
This project is dead, a fix for this problem was already included in the 'Pull Request' but the developer hasn't made an effort to merge the request. He said that he would look at it, in 2014 and never came back.

**Comment by dieulot** [comment]
I didn’t look at the issues/PR for a long time and ended up fixing it myself, the same way as you did, in 31eff8fd. Sorry for having let your PR slide.
