### ISSUE TITLE
Is this project no longer being developed?

### ISSUE THREAD

**Issue by QuantumRevenger** [dieulot/instantclick#139]
It seems that development has been dead for about a year now. Plentiful promises of 4.0 coming soon, with fixes to many issues; yet no sign of even a remote update from the developer.

Looks like I will be removing this from my site; there is no point using something as a foundation for your website knowing that its dead in the water.

Please give us an update at least on the status of 4.0?

**Comment by ttimasdf** [comment]
Yeah, it seems so. Take a look at the [Whois Record](http://www.whois.com/whois/instantclick.io). The domain name of it's official site is going near its expiry time. May indicates that the developer doesn't care it at all, even proclaim it depreciated.

**Comment by ttimasdf** [comment]
However is there an alternative?

**Comment by renatocarvalho** [comment]
I tried to find an alternative, but no luck.

**Comment by rofrnnds** [comment]
try these:
- https://github.com/turbolinks/turbolinks
- https://github.com/defunkt/jquery-pjax
- https://github.com/MoOx/pjax
- https://github.com/Easyfood/pageAccelerator
- https://github.com/ampproject/amphtml
- https://github.com/liferay/senna.js
- https://github.com/luruke/barba.js
- https://github.com/miguel-perez/smoothState.js

**Comment by dionysio** [comment]
There is also this fork [https://github.com/robgraeber/instantclick2](https://github.com/robgraeber/instantclick2) which offers:
* Preload caching, saves on unnecessary fetches by only loading pages once.
* Fix history bug when clicking on the same link multiple times.

**Comment by dieulot** [comment]
It’s still being developed. I am ashamed of having let this project languish like that. I am planning to write an explanation about this in the future.

**Comment by renatocarvalho** [comment]
@dieulot Awesome to hear from you! 👋

**Comment by onigetoc** [comment]
For alternative, if you have a Wordpress website try Zajax.
http://www.scriptsmashup.com/fr/product/zajax-ajax-navigation-plugin-for-wordpress
