### ISSUE TITLE
[Enhancement] TamperMonkey/GreaseMonkey Support

### ISSUE THREAD

**Issue by BetaLeaf** [dieulot/instantclick#142]
It would be nice to be able to load this javascript on all websites, not only ones specifically implementing it. A tool like TamperMonkey for Chrome and GreaseMonkey for Firefox would let the user inject javascript directly into all pages. This way all pages the user with the installed script they visited would load instantly.

**Comment by dieulot** [comment]
I’ve tried this, on one site that I don’t control. Unfortunately it was a disaster due to the JavaScript already there conflicting with InstantClick’s single-page application model, and there’s no way to patch that JavaScript.
