### ISSUE TITLE
When instantclick at the end of time, whether there is a corresponding function to load some incidents?

### ISSUE THREAD

**Issue by ihewro** [dieulot/instantclick#148]
When instantclick at the end of time, whether there is a corresponding function to load some incidents? For example, in the [`pjax project`](https://github.com/defunkt/jquery-pjax) :
```
$(document).on('pjax:complete', function() {
  $('#loading').hide()
})
```

**Comment by ihewro** [comment]
I see the answers in [issue #58](https://github.com/dieulot/instantclick/issues/58)  look forward to releasing the new version

**Comment by Tokinx** [comment]
你指的是这个嘛：
```
    InstantClick.on('wait', function() {
        // pjax href click
    });
    InstantClick.on('fetch', function() {
        // pjax begin
    });
    InstantClick.on('receive', function() {
        // pjax end
    });
```

**Comment by ihewro** [comment]
@Tokinx  thank you
