### ISSUE TITLE
Trying to request HTTP link

### ISSUE THREAD

**Issue by electricduck** [dieulot/instantclick#151]
Not sure if this is a bug, but I cannot work out what is wrong

All of my links do not have URLs in them (so, '/download', instead of 'https://mysite.com/download'), and the site is HTTPS. However, InstantClick is always trying to request the HTTP link and ultimately breaking.

**Comment by Harmonicorps** [comment]
Same here on my website. It keeps stripping https links and trying to request them as http instead, which my browser blocks.
