### ISSUE TITLE
blacklist class

### ISSUE THREAD

**Issue by novia713** [dieulot/instantclick#27]
hi! thanks for your effort, this project is awesome! :+1: 
how would be possible to blacklist a determined class in all links of a given site?
lets say the class i want to blacklist would be named "ajax" ...

**Comment by dieulot** [comment]
Stumbling on that issue now. I’ll detail how to do it (for those coming here from search engines).

jQuery:
```js
InstantClick.on('change', function() {
  $('.ajax').attr('data-no-instant', '');
});
```

Native, if you don’t need to support IE 8:
```js
InstantClick.on('change', function() {
  var elements = document.querySelectorAll('.ajax');
  for (var i = 0; i < elements.length; i++) {
    elements[i].setAttribute('data-no-instant', '');
  }
});
```

As with any code that happens on page change, this is to put after InstantClick’s core code and before `InstantClick.init()`.
