### ISSUE TITLE
Generated script link does not work

### ISSUE THREAD

**Issue by ianberdin** [dieulot/instantclick#41]
If the use of dynamic content, then it does not work.

**Comment by kapowaz** [comment]
@dieulot did this public interface to `InstantClick.instantanize()` get removed since you posted the above? I don't see it there in the [current release](http://instantclick.io/v3.1.0/instantclick.js).

**Comment by dieulot** [comment]
@kapowaz: What’s got into 3.1 is the handling of links inserted after InstantClick has initialized. I see no need for a public `instantanize` then. Do you have a case in mind when a public `instantanize` would be desirable despite this?
