### ISSUE TITLE
Breaks Facebook like button

### ISSUE THREAD

**Issue by nicoeg** [dieulot/instantclick#61]
When loading site my Facebook like button works, but when navigating to a new page, I just disapears.
Any way to fix that?

**Comment by shannont** [comment]
Just wondering, has this been fixed? I installed InstantClick on my website and was disappointed to find out that it breaks my Facebook and Twitter buttons. Is there a way to fix this yet? :(

**Comment by dieulot** [comment]
Not fixed yet. The list of workarounds for scripts I mention in my previous message is still planned, unfortunately last year I got distracted from InstantClick…

**Comment by rdpascua** [comment]
This also breaks functionality of Google Recaptcha

**Comment by luglio7** [comment]
You can try to inject the social js code after the page load via the instantclick change event. 
Haven't tested it but it should work.

**Comment by pranjitsingh** [comment]
Initially i used InstantClick.on('change',function(){ //CODE }); to load my social icons at http://www.invexnews.com/ , but after few days it started breaking on chrome browser.

When i have updated InstantClick.init(); line by InstantClick.init('mousedown'); , it started working on chrome too. :)

Conclusion : Preloading on mouseover (hover) which is enabled by Default seems culprit.

Regards,
Ranjit Singh

**Comment by misog** [comment]
Any workaround/fix now?

**Comment by IonicaBizau** [comment]
Any news on this? :thought_balloon:

**Comment by mauris** [comment]
Take a look at the updated link at http://instantclick.io/scripts

You probably need to re-init social plugins / other scripts using event handlers as described on that page.

**Comment by misog** [comment]
Hi, this works for me! And note that I changed sdk.js to all.js
```
	<script type="text/javascript">
		delete FB;
		$.getScript("//connect.facebook.net/en_US/all.js#xfbml=1&version=v2.6", function () {
			FB.init({ status: true, cookie: true, xfbml: true });
		});
	</script>
```

**Comment by AlexHodo** [comment]
@misog Thanks buddy! Been looking for it for days now!
