### ISSUE TITLE
Blacklisting through JavaScript doesn't work after first page

### ISSUE THREAD

**Issue by bui** [dieulot/instantclick#76]
I currently apply `data-no-instant` attributes to tags I want to blacklist before initializing, but after going through a page, InstantClick is already started before the blacklisting JS can be executed, so the tags aren't blacklisted.

Can something be done about this, without having to modify server-side code?

**Comment by dieulot** [comment]
This is now doable [on receive](http://instantclick.io/scripts#receive) in InstantClick 3.1!
