### ISSUE TITLE
Website title become URL in Chrome for iOS

### ISSUE THREAD

**Issue by shnjnchg** [dieulot/instantclick#79]
When I click any link at website, the title become URL:
<a href='http://postimg.org/image/lozmwxv6h/' target='_blank'><img src='http://s28.postimg.org/lozmwxv6h/instantclick_io.jpg' border='0' alt="instantclick io" /></a>

**Comment by mstratford** [comment]
Hi there,

This is still happening in the latest (and many previous builds) when going from the page to any subsequent pages in a tab. It only seems to happen on iPad (mine is a retina Mini 2 on iOS8).

Any ideas?
