### ISSUE TITLE
Horizontal scrollbar displayed on page load?

### ISSUE THREAD

**Issue by ghost** [dieulot/instantclick#91]

**Comment by floogulinc** [comment]
I am also having this issue. It appears to be from InstantClick. 

I tried to find what was creating the horizontal scroll bar, which allows you to scroll infinitely to the right, using this javascript in the browser console:
```js
var docWidth = document.documentElement.offsetWidth;

[].forEach.call(
  document.querySelectorAll('*'),
  function(el) {
    if (el.offsetWidth > docWidth) {
      console.log(el);
    }
  }
);
```

It didn't return anything before InstantClick had loaded a page (after a fresh reload). But after clicking a link and InstantClick loading it, the script returned this:
```html
<div id=​"instantclick" style=​"left:​ 0px;​ width:​ 558px;​ top:​ 0px;​ transform:​ scaleY(0.58125)​;​ opacity:​ 0;​">​<div id=​"instantclick-bar" class=​"instantclick-bar" style=​"transform:​ translate(100%)​;​">​</div>​</div>​

<div id=​"instantclick-bar" class=​"instantclick-bar" style=​"transform:​ translate(100%)​;​">​</div>​
```

My CSS is here: https://gist.github.com/floogulinc/5bd4cc68cb01edd18b34bd4519235f86
