### ISSUE TITLE
Programmatically open a URL

### ISSUE THREAD

**Issue by LouisMT** [dieulot/instantclick#97]
I have a form that I send to the server using jQuery. If the server validates the form it sends back a URL where the user should be redirected to.

Currently I'm using `window.location` for this. However, this way InstantClick is not used, so it feels slow in comparison to the pages.

It would be great if I could open a page with InstantClick programmatically:

```
InstantClick.go('/url/to/page');
```

_I guess it's also possible to create a hidden link and simulate a click on it, but that's not as nice as this._

**Comment by jondashkyle** [comment]
Would be great to have this!

**Comment by djlsa** [comment]
```javascript
InstantClick.go = function(url) {
	var link = document.createElement('a');
	link.href = url;
	document.body.appendChild(link);
	link.click();
}
```
